# Generated by Django 5.0.4 on 2026-09-04 16:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Cartões'},
        ),
        migrations.AlterField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='card',
            name='cvv',
            field=models.CharField(max_length=4, verbose_name='CVV'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiration_date',
            field=models.CharField(max_length=5, verbose_name='Data de expiração'),
        ),
        migrations.AlterField(
            model_name='card',
            name='holder_name',
            field=models.CharField(max_length=20, verbose_name='Titular'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='card',
            name='network',
            field=models.CharField(choices=[('V', 'Visa'), ('M', 'Mastercard')], max_length=1, verbose_name='Rede'),
        ),
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.CharField(max_length=16, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='card',
            name='status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovado'), ('E', 'Enviado'), ('R', 'Recebido')], default='P', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='card',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em'),
        ),
        migrations.AlterField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
